name: Build Shape Geoprocess
on:
  push:
    branches: [develop]
    paths:
      - 'shape_geoprocess/**'
      - '.github/workflows/shape-geoprocess-develop.yml'
  workflow_dispatch:
jobs:
  DockerImage:
    name: Shape Geoprocess Image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CASTLECI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CASTLECI_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CASTLECI_AWS_REGION }}
    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR (water-shape-geoprocess)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: water-shape-geoprocess
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest shape_geoprocess
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}